# Resources/config/services.yml
services:

    webeweb.highcharts-bundle.twig.extension.highcharts:
        class: WBW\HighchartsBundle\Twig\Extension\HighchartsTwigExtension
        arguments: ['@service_container']
        tags:
          - { name: twig.extension }
