# Resources/config/services.yml
services:

    webeweb.highcharts-bundle.twig.extension.highcharts:
        class: WBW\HighchartsBundle\Twig\Extension\HighchartsTwigExtension
        arguments: ["@=service('kernel').locateResource('@WBWHighchartsBundle/Resources')", "%kernel.environment%"]
        tags:
          - { name: twig.extension }
