# Resources/config/services.yml
services:

    webeweb.bundle.highchartsbundle.twig.extension.highcharts:
        class: WBW\Bundle\HighchartsBundle\Twig\Extension\HighchartsTwigExtension
        arguments: ["@=service('kernel').locateResource('@HighchartsBundle')", "%kernel.environment%"]
        tags:
          - { name: twig.extension }
